name: Deploy Backend

on:
  push:
    branches: [main]
    paths: 
      - 'backend/**'
      - 'packages/core/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [main]
    paths: 
      - 'backend/**'
      - 'packages/core/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test Core
        run: npm run test:core
      
      - name: Test Backend
        run: npm run test:backend
      
      - name: Lint Backend
        run: npm run lint --workspace=backend

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Core
        run: npm run build --workspace=@grocery-store/core
      
      - name: Build Backend
        run: npm run build --workspace=backend
      
      - name: Deploy to Production
        run: |
          echo "Deploying backend to production..."
          # Add your deployment commands here
          # Example: docker build, kubectl apply, etc.
